# SPDX-License-Identifier: BSD-3-Clause
# Oracolo di GlifiNetworkExtensionsTests: eigen() di base e igraph (modularità, Louvain,
# cammini pesati con distanza 1/peso, eigen_centrality pesata, componenti).
source(file.path(dirname(sub("--file=", "", grep("--file=", commandArgs(FALSE), value = TRUE))), "common.R"))
A <- matrix(c(0, 2, 1, 0, 2, 0, 1, 1, 1, 1, 0, 3, 0, 1, 3, 0), 4, byrow = TRUE)
e <- eigen(A); v <- abs(e$vectors[, 1]); emit("EIGEN_WEIGHTED", c(e$values[1], v / max(v)))
suppressMessages(library(igraph))
g <- make_graph("Zachary")
emit("INFO_KARATE_EDGES", as.vector(t(as_edgelist(g))) - 1)
set.seed(1); emit("KARATE_LOUVAIN_Q", modularity(cluster_louvain(g)))
faction <- c(1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2)
emit("KARATE_FACTION_Q", modularity(g, faction))
w <- data.frame(a = c(1, 1, 2, 2, 3, 4, 4, 5), b = c(2, 3, 3, 4, 5, 5, 6, 6), w = c(3, 1, 1, 2, 4, 1, 2, 1))
h <- graph_from_data_frame(w, directed = FALSE, vertices = data.frame(n = 1:6))
emit("WEIGHTED_BETWEENNESS_UNDIRECTED", betweenness(h, weights = 1 / E(h)$w))
emit("WEIGHTED_HARMONIC", harmonic_centrality(h, weights = 1 / E(h)$w))
ec <- eigen_centrality(h, weights = E(h)$w); emit("WEIGHTED_EIGEN", c(ec$value, ec$vector))
emit("WEIGHTED_SPLIT_Q", modularity(h, c(1, 1, 1, 2, 2, 2), weights = E(h)$w))
d <- make_graph(c(1, 2, 2, 3, 3, 1, 3, 4, 5, 6, 6, 5), n = 7, directed = TRUE)
emit("COMPONENTS", c(components(d, "weak")$no, components(d, "strong")$no))
# Grafo casuale grande (seed 42): dati di massa letti direttamente da GlifiNetworkScaleTests.
set.seed(42)
big <- sample_gnm(150, 600)
E(big)$weight <- round(runif(ecount(big), 0.1, 5), 2)
emit("INFO_BULK_EDGES", as.vector(t(cbind(as_edgelist(big) - 1, E(big)$weight))))
emit("INFO_BULK_BETWEENNESS", betweenness(big, weights = 1 / E(big)$weight))
emit("INFO_BULK_HARMONIC", harmonic_centrality(big, weights = 1 / E(big)$weight))
set.seed(1)
emit("INFO_BULK_LOUVAIN_Q", modularity(cluster_louvain(big, weights = E(big)$weight), weights = E(big)$weight))
emit("INFO_BULK_COMPONENTS", components(big)$no)
